"""Add currency and portfolio fields to users

Revision ID: 21a70d2d022c
Revises: 8f125caefc43
Create Date: 2025-07-05 11:44:00.564130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21a70d2d022c'
down_revision: Union[str, Sequence[str], None] = '8f125caefc43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('currency', sa.String(length=3), nullable=False, server_default="USD"))
    op.add_column('users', sa.Column('savings_goal', sa.Float(), nullable=False, server_default="100"))
    op.add_column('users', sa.Column('sparevest_balance', sa.Float(), nullable=False, server_default="0"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sparevest_balance')
    op.drop_column('users', 'savings_goal')
    op.drop_column('users', 'currency')
    # ### end Alembic commands ###
