"""rename price_history columns only

Revision ID: 375db7ab7eee
Revises: b67e15eb1a52
Create Date: 2025-07-16 10:05:40.452244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '375db7ab7eee'
down_revision: Union[str, Sequence[str], None] = 'b67e15eb1a52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_history', sa.Column('open_price', sa.Numeric(), nullable=True))
    op.add_column('price_history', sa.Column('high_price', sa.Numeric(), nullable=True))
    op.add_column('price_history', sa.Column('low_price', sa.Numeric(), nullable=True))
    op.add_column('price_history', sa.Column('volume', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_history', 'volume')
    op.drop_column('price_history', 'low_price')
    op.drop_column('price_history', 'high_price')
    op.drop_column('price_history', 'open_price')
    # ### end Alembic commands ###
