"""Transaction schema update

Revision ID: 4905954ba781
Revises: 21a70d2d022c
Create Date: 2025-07-05 22:22:10.730735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4905954ba781'
down_revision: Union[str, Sequence[str], None] = '21a70d2d022c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transactions', 'created_at')
    # ### end Alembic commands ###
