"""Portfolio schema

Revision ID: 495321ca98cf
Revises: 4905954ba781
Create Date: 2025-07-07 11:01:16.467264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '495321ca98cf'
down_revision: Union[str, Sequence[str], None] = '4905954ba781'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('type', sa.String(), nullable=False))
    op.drop_column('users', 'sparevest_balance')
    op.drop_column('users', 'savings_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('savings_goal', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'100'::double precision"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('sparevest_balance', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0'::double precision"), autoincrement=False, nullable=False))
    op.drop_column('transactions', 'type')
    # ### end Alembic commands ###
