"""add last quote fields to stock

Revision ID: 55d095397ce8
Revises: d570a8d5cfab
Create Date: 2025-07-14 18:40:54.094642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55d095397ce8'
down_revision: Union[str, Sequence[str], None] = 'd570a8d5cfab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('last_price', sa.Numeric(), nullable=True))
    op.add_column('stock', sa.Column('day_open', sa.Numeric(), nullable=True))
    op.add_column('stock', sa.Column('day_high', sa.Numeric(), nullable=True))
    op.add_column('stock', sa.Column('day_low', sa.Numeric(), nullable=True))
    op.add_column('stock', sa.Column('prev_close', sa.Numeric(), nullable=True))
    op.add_column('stock', sa.Column('quote_fetched_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'quote_fetched_at')
    op.drop_column('stock', 'prev_close')
    op.drop_column('stock', 'day_low')
    op.drop_column('stock', 'day_high')
    op.drop_column('stock', 'day_open')
    op.drop_column('stock', 'last_price')
    # ### end Alembic commands ###
