"""Fix Stock.transactions relationship

Revision ID: d570a8d5cfab
Revises: e7df1adec60e
Create Date: 2025-07-14 04:15:34.133529

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd570a8d5cfab'
down_revision: Union[str, Sequence[str], None] = 'e7df1adec60e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
